# Generated by Django 3.0.8 on 2020-07-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200723_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Report',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
