# Generated by Django 3.0.8 on 2020-07-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200723_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Report')),
            ],
        ),
    ]
